name: Pull from hatena blog

on:
  workflow_run:
    workflows: ["Push to hatena blog"]
    branches-ignore: 
      - main
    types: 
      - completed
      # - requested
  schedule:
    - cron: '*/5 * * * *'

jobs:

  pull:
    name: Pull
    runs-on: ubuntu-latest
    env:
      BSY: ${{ secrets.BSY }}
      DOMAIN: ${{ secrets.DOMAIN }}
      TZ: "Asia/Tokyo"
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Debug
      run: git log | head -1

    - name: Setup blogsync
      run: |
        go get github.com/motemen/blogsync        
        echo -e ${BSY} > blogsync.yaml

    - name: Pull
      run: ~/go/bin/blogsync pull ${DOMAIN}

    - name: Run git status
      id: status
      run: echo "::set-output name=status::$(git status -s)"

    - name: Add and commit files
      run: |
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Update entries at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")"
      if: ${{ steps.status.outputs.status }}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
      if: ${{ steps.status.outputs.status }}

    # - name: notify to slack
    #   uses: mm0202/action_slack-notify@master
    #   if: always()
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}