name: Push to hatena blog

on: 
  push:
    branches-ignore:
      - main

jobs:

  push:
    name: Push
    runs-on: ubuntu-latest
    env:
      BSY: ${{ secrets.BSY }}
      DOMAIN: ${{ secrets.DOMAIN }}
      TZ: "Asia/Tokyo"
      DRAFT: draft.md
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - run: git fetch origin main

    - name: Setup blogsync
      run: |
        go get github.com/motemen/blogsync
        echo -e ${BSY} > blogsync.yaml

    - name: push
      run: |
        git config --global core.quotepath false
        git diff origin/main --name-only --diff-filter=ACMR \
        | grep entries/${DOMAIN}/entry \
        | xargs -t -n1 ~/go/bin/blogsync push

    - name: Check if ${DRAFT} is modified
      id: draft
      run: echo "::set-output name=draft::$(git diff origin/main --name-only --diff-filter=ACMR ${DRAFT})"

    - name: post from ${DRAFT}
      run: |
        export TITLE=$(grep  "^Title:" ${DRAFT} | sed -e 's/^Title:\ //g')
        export ENTRY_PATH=$(date '+%Y/%m/%d')/$(echo ${TITLE} | sed -e "s/\ /_/g")
        ~/go/bin/blogsync post --title=${TITLE} --draft --custom-path=${ENTRY_PATH} ${DOMAIN} < ${DRAFT}
      if: ${{ steps.status.outputs.draft }}

    # - name: notify to slack
    #   uses: mm0202/action_slack-notify@master
    #   if: always()
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}